### ISSUE TITLE
[queue_next] I had a problem handling "n"

### ISSUE THREAD

**Issue by jelmerdereus** [osteenbergen/slackify#22]
I saw this in the Slack channel. There seems to be a timeout issue.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/slackbot/dispatcher.py", line 55, in _dispatch_msg_handler
    func(Message(self._client, msg), *args)
  File "/home/divider/slackify/plugins/queue.py", line 79, in queue_next
    return slackify.player.play(nxt.song, QueueManager.MODE_RANDOM)
  File "/home/divider/slackify/lib/spotifyplayer.py", line 106, in play
    trackdata = self.session.get_track(song.uri).load()
  File "/usr/lib/python2.7/dist-packages/spotify/track.py", line 81, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/spotify/utils.py", line 246, in load
    raise spotify.Timeout(timeout)
Timeout: Operation did not complete in 10.000s
```

**Comment by osteenbergen** [comment]
Internet connection had some issues, need to improve the error catching.
